# Calibo AI Academy — Pandas Assignment
## Phase 1 | Module 3 | Unit 1

**Name:** Nuthakki Venkata Uma Sai Subrahmanyam  
**Batch:** Batch-2   
**Branch:** IT

#  Section-A: Output Prediction.
## Q1.  Array operations and vectorization

### Predicted Output:

[20 40 60]  
0      20  
1      40  
2      60  
dtype: int64


#### Similarity:
* Both performs element wise multiplication by 2

#### Difference:
* NumPy array has positional elements only, whereas a Pandas Series has an index associated with each value.

In [30]:
import numpy as np
import pandas as pd

arr = np.array([10, 20, 30])
s = pd.Series([10, 20, 30])

print(arr * 2)
print(s * 2)



[20 40 60]
0    20
1    40
2    60
dtype: int64


## Explanation:
**Numpy:** Numpy stores the elements in the array  
**Pandas:** Pandas stores the elements with the associated index.

## Q2. Boolean Filtering

### Predicted Output:

   Student    Marks  
 1         B       80  
 2         C       65  
 3         D       90  



#### Rows Displayed:
* All the rows are displayed because all rows satisfies the condition.

**How many rows and columns will the resulting DataFrame contain?**

* The resulting dataframe contains 3 rows and 2 columns.




In [31]:
import pandas as pd

df = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D'],
    'Marks': [45, 80, 65, 90]
})

result = df[df['Marks'] >= 65]

print(result[['Student', 'Marks']])


  Student  Marks
1       B     80
2       C     65
3       D     90


### Explanation:
* The condition Marks>=65 selects students whose marks are at least 65.
* If the condition satisfies then it will returns the rows.

## Q3.  Descriptive statistics

### Predicted Output:
* Mean is  30.0
* Max is 50
* Median id 30.0



### Explain how the median differs from the mean.
* Mean uses every value to calculate the average, while median identifies the middle value after sorting the data.




In [32]:
import pandas as pd

df = pd.DataFrame({
    'Marks': [10, 20, 30, 40, 50]
})

print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].median())


30.0
50
30.0


### Explanation:
 * By using the mean() we can get the mean of the whole DataFrame,
 *  max() gives the maximum value in the whole DataFrame,
 * median() gives the middle value of the DataFrame.

## Q4.  Group-wise Analysis

### Predicted Output:
* Department
* HR    40000.0
* IT    50000.0
* Name: Salary, dtype: float64

### Explain how groupby() calculated the department-wise average.
* groupby() groups rows by departments
* mean() calculated the average salary within each group.

In [33]:
import pandas as pd

df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'HR'],
    'Salary': [40000, 30000, 60000, 50000]
})

print(df.groupby('Department')['Salary'].mean())


Department
HR    40000.0
IT    50000.0
Name: Salary, dtype: float64


### Explanation:

* The groupby is used to groupby based on the departments in the DataFrame and gives the average salary based on the Departments.

## Q5. Positive Correlation

### Predicted Output:

* 1.0
### Interpret the direction and strength of the relationship.

* As study hours increase, marks increase proportionally.





In [34]:
df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks']))

1.0


### Explanation:
* There are two types of correlations 1.Perfect Positive linear and 2. Perfect Negative linear.
* The correlation is +1, indicating a perfect positive linear.

## Q6. Negative Correlation

### Predicted Output:

* -1.0

### Explain what the sign of the coefficient indicates about the relationship.

* As proce increases, demand decreases.

In [35]:
import pandas as pd
df = pd.DataFrame({
    'Price': [10, 20, 30, 40],
    'Demand': [100, 80, 60, 40]
})
print(df['Price'].corr(df['Demand']))

-1.0


Explanation:
* There are two types of correlations 1.Perfect Positive linear and 2. Perfect Negative linear.
* The correlation is -1, indicating a perfect positive linear.

# Section B – Code Correction

## Q1. JSON and CSV Header

####  A CSV file contains a header row, but the following code incorrectly reads the first student's record as column names. Correct the code.

* If we add the header=0 the it will automatically assumes the first rows is column names.

In [56]:
import pandas as pd

df = pd.read_csv("students.csv",header=0)
print(df)

    ID     Name        Date  Marks
0  101  Asha, R  2026-09-01   80.0
1  102     Ravi  01/09/2026    NaN
2  103     Neha  2026-09-03    NaN


### Explanation:
* header=0 tells Pandas that the first row contains column names. The default behavior of read_csv() already assumes this.

# Q2. Data Analysis



### The objective is to display the five highest salaries from a DataFrame.

* If we add the ascending = False then it will automatically sort the salries and displays the first five rows using the head() function.

In [58]:
import pandas as pd

df = pd.DataFrame({
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [30000, 50000, 25000, 60000, 45000, 70000]
})

print(df.sort_values('Salary',ascending=False).head(5))                              


  Employee  Salary
5        F   70000
3        D   60000
1        B   50000
4        E   45000
0        A   30000


### Explanation:

* df.sort_values() function is used to sort the values in the DataFrame in ascending or descending order. and head() function is used to display the top five rows in the DataFrame.

# Q3. Cleaning Data          



#### A student wants to replace missing marks with the column's mean but writes code that does not update the DataFrame. Correct the code. 

* The mean of 70 and 90 is 80, so the missing value is replaced with 80.



In [38]:
import pandas as pd

df = pd.DataFrame({'Marks': [70, None, 90]})
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
print(df)
  


   Marks
0   70.0
1   80.0
2   90.0


### Explantion:

* fillna() returns a modified series but does notupdate the original DataFrame unless assigned and it assigns the missing values with the mean values.

# Q4. Correlation

**The objective is to calculate the correlation between Hours and Marks**



In [39]:
import pandas as pd
df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})
print(df['Hours'].corr(df['Marks']))



1.0


### Explanation:

* The two columns have a perfect positive linear relationship. Because the correlation between the hours and marks is 1.0.

# Section-C:Edge Cases

### Q1. Two NumPy arrays have shapes (3, 1) and (1, 3). Predict the shape of their element-wise sum and explain how broadcasting works. Why might the result differ from adding two one-dimensional arrays?

**1.Predict the output of the given code.**  
[[11 12 13]  
 [21 22 23]  
 [31 32 33]]  
 * The shape of the result is (3,3).

#### Explanation: 
* Numpy uses broadcasting to make the two arrays compactible for addition.

**2.Identify the shapes of arrays a and b before addition.**
* The shape of the array a before addition is `(3,1)`
* The shape of the array b before addition is`(1,3)`

**3.Explain how NumPy broadcasting enables the addition.**
* NumPy broadcasting expands the compatible dimensions to perform `element-wise addition`, producing a (3, 3) array.

 **4.What happens if b is replaced with np.array([1, 2])?**
* The shapes cannot be broadcast together because the dimensions are incompatible. A ValueError occurs.



In [40]:
import numpy as np
a = np.array([[10], [20], [30]])
b = np.array([[1, 2, 3]])
result = a + b
print(result)
print(result.shape)


[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)


### Explanation:
* Broadcasting allows Numpy to perform the element-wise operations on arrays with compactible but different shapes. In this example (3,1) and (1,3) broadcast to (3,3).

##### Q2. A CSV file contains commas inside quoted text fields, missing values, and dates in different formats. Explain how incorrect parsing can affect the resulting DataFrame and identify suitable read options or preprocessing steps.
- CSV files may contain inconsistent date formats, missing values, and text in numeric columns. 
- Pandas provides functions to parse dates, convert values into appropriate data types, and identify missing data for further analysis.

In [41]:
import pandas as pd

df = pd.read_csv("students.csv")

print(df)
print(df.dtypes)


    ID     Name        Date  Marks
0  101  Asha, R  2026-09-01   80.0
1  102     Ravi  01/09/2026    NaN
2  103     Neha  2026-09-03    NaN
ID         int64
Name         str
Date         str
Marks    float64
dtype: object


**1.Predict how the quoted comma in "Asha, R" will be handled when the CSV file is read.**  
The quoted comma in "Asha, R" is handled correctly by `read_csv()` and remains part of the name.

**2.Identify the potential issues with the Date and Marks columns.**  
The Date column contains different date formats, so dates should be converted into a consistent datetime format. The intended day/month order must be confirmed because dates can be ambiguous.

**3. Rewrite the code to handle missing marks and convert the date column into a suitable date-time format.**   
The Marks column contains missing values. `pd.to_numeric(errors="coerce")` converts invalid or non-numeric values to `NaN`.

In [42]:
import pandas as pd
df = pd.read_csv("students.csv")
df["Date"] = pd.to_datetime(
    df["Date"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)
df["Marks"] = pd.to_numeric(
    df["Marks"],
    errors="coerce"
)
print(df)
print(df.dtypes)
print(df.isnull().sum())

    ID     Name       Date  Marks
0  101  Asha, R 2026-01-09   80.0
1  102     Ravi 2026-09-01    NaN
2  103     Neha 2026-03-09    NaN
ID                int64
Name                str
Date     datetime64[us]
Marks           float64
dtype: object
ID       0
Name     0
Date     0
Marks    2
dtype: int64


**4. Explain why the value "NA" should be investigated before deciding whether it represents a missing value.**  
The value `"NA"` should be investigated to determine whether it means a missing mark or represents another category.

##### Q3. A salary column contains the values 25000, 30000, 35000, and 10000000. Explain how the extreme value affects the mean compared with the median. Identify which statistic may better represent a typical employee's salary and justify your choice.
- Outliers are extreme values that can significantly affect statistical calculations.
- Comparing the mean and median helps understand their impact, as the median is generally less affected by unusually large or small values.

In [43]:
import pandas as pd
df = pd.DataFrame({
    "Employee": ["A", "B", "C", "D"],
    "Salary": [25000, 30000, 35000, 10000000]
})
print("Mean:", df["Salary"].mean())
print("Median:", df["Salary"].median())

Mean: 2522500.0
Median: 32500.0


**1. Predict the mean and median salary.**  
Mean: 2522500.0  
Median: 32500.0  

**2. Identify the effect of the extreme salary on the mean.**  
The extreme salary of 10,000,000 increases the mean significantly.  

**3. Which statistic may better represent a typical employee's salary in this dataset? Justify your answer.**  
The median may better represent a typical employee's salary because it is less affected by extreme values.

**4. Write code to identify the employee record with the highest salary and explain why the record should be investigated before removing it.**  
The highest salary should be investigated before removing it, because it could be a genuine salary rather than a `data-entry error`.

In [44]:
import pandas as pd
df = pd.DataFrame({
    "Employee": ["A", "B", "C", "D"],
    "Salary": [25000, 30000, 35000, 10000000]
})
print("Mean:", df["Salary"].mean())
print("Median:", df["Salary"].median())
highest_salary = df.loc[df["Salary"].idxmax()]
print("\nEmployee with highest salary:")
print(highest_salary)

Mean: 2522500.0
Median: 32500.0

Employee with highest salary:
Employee           D
Salary      10000000
Name: 3, dtype: object


## Section D – Scenario-based Questions

##### Q1. A student assessment dataset contains missing marks, duplicate student records, inconsistent department names such as IT, it, and I.T., and marks stored as text. Develop a cleaning sequence to standardize the data, handle missing values, remove duplicates, and convert marks into a suitable numeric type. State one risk of deleting missing values without investigating why they are missing. 

The dataset contains several data-quality issues, including missing marks, duplicate records, inconsistent department names, and marks stored as text. The cleaning process involves inspecting the dataset, standardizing department names, removing duplicate records, converting marks into numeric values, investigating missing data, and identifying marks outside the valid range of 0–100.

**1. Load the CSV file and inspect the dataset using head(), info(), and isnull().sum().** 

In [45]:
import pandas as pd
df = pd.read_csv("student_assessment_dirty.csv")
print("First five rows:")
print(df.head())
print("\nDataset information:")
df.info()
print("\nMissing values:")
print(df.isnull().sum())

First five rows:
  Student_ID Student_Name Department Assessment   Marks
0       S101         Asha         IT     Python      85
1       S102         Ravi         it     Python      78
2       S103         Neha       I.T.     Python      92
3       S104        Karan         HR     Python     NaN
4       S105        Meera         HR     Python  Absent

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_ID    15 non-null     str  
 1   Student_Name  15 non-null     str  
 2   Department    15 non-null     str  
 3   Assessment    15 non-null     str  
 4   Marks         12 non-null     str  
dtypes: str(5)
memory usage: 732.0 bytes

Missing values:
Student_ID      0
Student_Name    0
Department      0
Assessment      0
Marks           3
dtype: int64


##### Explanation:
- The Pandas library is imported to perform data-cleaning operations, and the CSV file is loaded into a DataFrame.
- `head()` displays the first five rows, `info()` provides information about columns and data types, and `isnull().sum()` counts missing values in each column.

**2. Standardize department names so that IT, it, and I.T. are represented consistently. Apply the same approach to Finance.**  

In [46]:
df["Department"] = (
    df["Department"]
    .str.strip()
    .str.upper()
    .replace({"I.T.": "IT"})
)
print(df["Department"].value_counts())

Department
IT         7
HR         4
FINANCE    4
Name: count, dtype: int64


##### Explanation:
Department names are converted to uppercase, and I.T. is replaced with IT. This ensures that IT, it, and I.T. are represented consistently. Finance variations are also standardized as FINANCE.

**3.Identify and remove exact duplicate student assessment records.**  

In [47]:
original_count = len(df)
df = df.drop_duplicates().copy()
records_removed = original_count - len(df)
print("Records removed:", records_removed)

Records removed: 1


##### Explanation: 
`drop_duplicates()` removes exact duplicate records. The difference between the original and cleaned row counts gives the number of records removed.

**4. Convert the Marks column into a numeric format, handling "88 marks", "Absent", "NA", and blank entries appropriately.**

In [48]:
marks_text = (
    df["Marks"]
    .astype("string")
    .str.strip()
    .str.replace(r"\s*marks\s*$", "", regex=True, case=False)
)
df["Marks"] = pd.to_numeric(
    marks_text.replace({
        "Absent": pd.NA,
        "NA": pd.NA,
        "": pd.NA
    }),
    errors="coerce"
)

##### Explanation:
The text " marks" is removed from entries such as "88 marks". The remaining values are converted into numeric form, while Absent, NA, blank entries, and other `unconvertible values` become missing numeric values.

**5. Investigate missing marks and distinguish absent students from students whose marks have not been entered. State one risk of deleting missing values without investigating why they are missing.**  

In [49]:
df["Attendance_Status"] = "Marks entered"
df.loc[
    marks_text.str.casefold().eq("absent").fillna(False),
    "Attendance_Status"
] = "Absent"
missing_mask = (
    marks_text.isna()
    | marks_text.eq("")
    | marks_text.str.casefold().eq("na").fillna(False)
)
df.loc[missing_mask, "Attendance_Status"] = "Marks not entered"
print(df[["Student_ID", "Student_Name", "Marks", "Attendance_Status"]])

   Student_ID Student_Name  Marks  Attendance_Status
0        S101         Asha     85      Marks entered
1        S102         Ravi     78      Marks entered
2        S103         Neha     92      Marks entered
3        S104        Karan   <NA>  Marks not entered
4        S105        Meera   <NA>             Absent
5        S106        Arjun      0      Marks entered
6        S107        Priya     67      Marks entered
7        S108        Rahul     75      Marks entered
9        S109        Sneha   <NA>  Marks not entered
10       S110        Varun     88      Marks entered
11       S111         Diya     91      Marks entered
12       S112         Aman   <NA>  Marks not entered
13       S113        Nisha     64      Marks entered
14       S114        Kabir    105      Marks entered


##### Explanation:
The Attendance_Status column distinguishes students recorded as absent from those whose marks have not been entered. This prevents different reasons for missing marks from being treated as identical.

> Risk: Deleting missing values without investigation may remove useful student records and introduce bias into the analysis.

**6.Identify marks outside the valid range of 0–100 and decide how they should be handled.**

In [50]:
invalid_mask = df["Marks"].notna() & (
    (df["Marks"] < 0) | (df["Marks"] > 100)
)

invalid_marks = df.loc[invalid_mask]

print("Invalid marks:")
print(invalid_marks[["Student_ID", "Student_Name", "Marks"]])

df["Invalid_Marks"] = invalid_mask


Invalid marks:
   Student_ID Student_Name  Marks
14       S114        Kabir    105


##### Explanation:
Marks `below 0 or above 100` are identified as invalid. These records are flagged for investigation instead of being automatically deleted, because they may contain data-entry errors.

**7.Display the cleaned DataFrame and report the number of records removed, missing marks remaining, and invalid marks identified.**

In [51]:
print("\nCleaned DataFrame:")
print(df)
print("\nRecords removed:", records_removed)
print("Missing marks remaining:", df["Marks"].isna().sum())
print("Invalid marks identified:", invalid_mask.sum())


Cleaned DataFrame:
   Student_ID Student_Name Department Assessment  Marks  Attendance_Status  \
0        S101         Asha         IT     Python     85      Marks entered   
1        S102         Ravi         IT     Python     78      Marks entered   
2        S103         Neha         IT     Python     92      Marks entered   
3        S104        Karan         HR     Python   <NA>  Marks not entered   
4        S105        Meera         HR     Python   <NA>             Absent   
5        S106        Arjun    FINANCE     Python      0      Marks entered   
6        S107        Priya    FINANCE     Python     67      Marks entered   
7        S108        Rahul         IT     Python     75      Marks entered   
9        S109        Sneha         IT     Python   <NA>  Marks not entered   
10       S110        Varun         HR     Python     88      Marks entered   
11       S111         Diya    FINANCE     Python     91      Marks entered   
12       S112         Aman         IT     Py

### Overall Explanation For Section D
- **Department names:** Convert names to uppercase and standardize I.T. as IT. This also standardizes Finance and finance as FINANCE.

- **Duplicates:** drop_duplicates() removes exact duplicate records.

- **Marks conversion:** Removes the text "marks" from values such as "88 marks" and converts the column to numeric. Absent, NA, and blank entries are treated as missing numeric marks.

- **Missing values:** The Attendance_Status column distinguishes students marked absent from students whose marks were not entered.

- **Invalid marks:** Values below 0 or above 100 are flagged for verification. They should not be deleted automatically because they may represent data-entry errors.

- **Risk of deleting missing rows:** It can remove useful student records and introduce bias if missing marks are related to absence or incomplete data entry.

# ---------------------------------End Of the Assignment-------------------------------